### ISSUE TITLE
Brownie doesn't work

### ISSUE THREAD

**Issue by batuhan** [tapquo/Lungo.js#178]
I'm trying to build from this repo (with latest versions of grunt and grunt-contrib), it doesn't fail but the result CSS is broken.

it looks like this: 

![Screen Shot 2013-04-08 at 20 01 25](https://f.cloud.github.com/assets/535988/352775/fe8f6d58-a06d-11e2-868f-3a9e76394959.png)

if I download the CSS from @soyjavi's "lungo.brownie" repo, and change it with the one created by grunt, it works.

also difference between those codes are these lines:

``` css
body > section.show{-webkit-animation:showing 400ms;-moz-animation:showing 400ms;-ms-animation:showing 400ms;-o-animation:showing 400ms;animation:showing 400ms;-webkit-animation-fill-mode:forwards;-moz-animation-fill-mode:forwards;-ms-animation-fill-mode:forwards;-o-animation-fill-mode:forwards;animation-fill-mode:forwards;display:-webkit-box;display:-moz-box;display:-ms-box;display:-o-box;display:box}
body > section.hide{-webkit-animation:hiding 400ms;-moz-animation:hiding 400ms;-ms-animation:hiding 400ms;-o-animation:hiding 400ms;animation:hiding 400ms}
```

But adding this CSS breaks asides on small screens.
