### ISSUE TITLE
SplitView

### ISSUE THREAD

**Issue by ceritium** [tapquo/Lungo.js#7]
I think that Split View may be interesting, with this little code we can see an example, try only on tablets.

``` css
section.split article {
  margin-left: 20%;
}

section.split nav {
  width: 20%;
  top: 40px;
  position: absolute;
}

section.split nav a {
  height: auto;
  width: 100%;
  text-align: left;
}
```

``` haml
%section#welcome.split
  %header{"data-title" => "Welcome"}

  %nav
    %scroll#options_scroll
      %a.current{:href => "#"} option 1
      %a.current{:href => "#"} option 2
      %a.current{:href => "#"} option 3

  %article
    %a.section.button.big{"data-icon" => "facebook", :href => "#events"} Facebook Login
    %a.section.button.big{"data-icon" => "home", :href => "#events"} Twitter Login
    %a.section.button.big{"data-icon" => "help", :href => "#events"} About
```

Show or hide the menu based on the width of the device can easily be done by javascript.

But most importantly, Do you consider Lungojs should be directed to tablets?
